services:
  db: 
    image: postgres:15
    container_name: db
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  db_test: 
    image: postgres:15
    container_name: db_test
    environment:
      - POSTGRES_DB=db_test
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"